### ISSUE TITLE
python 3 support for histogram dependencies

### ISSUE THREAD

**Issue by yxqd** [danse-inelastic/histogram#36]
* [x] danse.ins danse-inelastic/danse.ins#2
* [x] journal danse-inelastic/journal#11
* [x] pyre danse-inelastic/pyre#13
